on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  pyinstaller-build-mac:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: unofficial-rev-port/pyinstaller@v1.2
        with:
          python_ver: "3.12"
          pyinstaller_ver: "==6.6.0"
          spec: "lzcommit.spec"
          clean_checkout: false
          upload_exe_with_name: "lzcommit_mac"
      - name: Make DMG
        uses: unofficial-rev-port/create-dmg-action-fixed-icon@v0.1.0
        with:
          name: "lzcommit"
          srcdir: "./dist/lzcommit.app"
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: "lzcommit"
          path: "./lzcommit.dmg"
  pyinstaller-build-win:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: unofficial-rev-port/pyinstaller@v1.2
        with:
          python_ver: "3.12"
          pyinstaller_ver: "==6.6.0"
          spec: "lzcommit.spec"
          clean_checkout: false
          upload_exe_with_name: "lzcommit_win.exe"
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: unofficial-rev-port/pyinstaller@v1.2
        with:
          python_ver: "3.12"
          pyinstaller_ver: "==6.6.0"
          spec: "lzcommit.spec"
          clean_checkout: false
          upload_exe_with_name: "lzcommit"
